# Generated by Django 5.1.3 on 2024-11-21 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_appointment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("user_role__role_name", "Customer")),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
