# Generated by Django 5.1.3 on 2024-11-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_appointmentstaff"),
        ("services", "0003_remove_service_applied_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="services.coupon",
            ),
        ),
    ]
