# Generated by Django 5.1.3 on 2024-11-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("cash", "Cash"),
                    ("mobile_payment", "Mobile Payment"),
                    ("paypal", "PayPal"),
                ],
                max_length=50,
            ),
        ),
    ]
