# Generated by Django 5.1.3 on 2024-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="applied_coupon_code",
            field=models.CharField(
                blank=True,
                help_text="Coupon code entered by user for this service",
                max_length=50,
                null=True,
            ),
        ),
    ]
