# Generated by Django 5.1.3 on 2024-11-19 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_applied_coupon_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="max_staff_allowed",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="service",
            name="min_staff_required",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ServiceStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("can_perform_service", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="services.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Service Staff",
                "unique_together": {("service", "staff")},
            },
        ),
        migrations.AddField(
            model_name="service",
            name="staff",
            field=models.ManyToManyField(
                help_text="Staff members who can perform this service",
                related_name="assigned_services",
                through="services.ServiceStaff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
