# Generated by Django 5.1.3 on 2024-11-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0004_service_max_staff_allowed_service_min_staff_required_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="service",
            name="max_staff_allowed",
        ),
        migrations.RemoveField(
            model_name="service",
            name="min_staff_required",
        ),
        migrations.DeleteModel(
            name="ServiceStaff",
        ),
    ]
