# Generated by Django 5.1.3 on 2024-12-01 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_service_applied_coupon_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffservice",
            name="staff",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("user_role__role_name", "Customer"), _negated=True
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
