# Generated by Django 5.1.3 on 2024-12-03 07:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_staffservice_staff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffservice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="staffservice",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="staffservice",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="staffservice",
            name="start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="staffservice",
            name="status",
            field=models.CharField(
                choices=[("working", "Working"), ("not_working", "Not Working")],
                default="not_working",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffservice",
            unique_together={("staff", "service", "date", "start_time", "end_time")},
        ),
    ]
