# Generated by Django 5.1.3 on 2024-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0002_alter_service_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='services.service'),
        ),
    ]
